### ISSUE TITLE
cloud-init iso inject failed

### ISSUE THREAD

**Issue by abrahamhwj** [ionos-cloud/cluster-api-provider-proxmox#225] opened 2024-06-03 03:26 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The error message when using the Proxmox provider to create a cluster suggests: failed to inject cloud-init ISO.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The operator error log：
"Reconciler error" err="failed to reconcile VM: cloud-init iso inject failed: unable to inject CloudInit ISO: bad request: 400 Parameter verification failed. - {\"boot\":\"invalid format - format error\\nboot.legacy: value does not match the regex pattern\\n\"}" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/proxmox-quickstart-control-plane-rqxgq" namespace="default" name="proxmox-quickstart-control-plane-rqxgq" reconcileID="8ca71cce-ba7c-4921-a7db-171a37a5a62b"
![image](https://github.com/ionos-cloud/cluster-api-provider-proxmox/assets/40071638/9beba85f-f105-409a-aedb-bdb7ebf2cc19)

**Environment:**
VM Template script：
qm create 9000 --memory 4096 --cores 4 --net0 virtio,bridge=vmbr0
qm disk import 9000 CentOS-7-x86_64-GenericCloud.qcow2c local-lvm
qm set 9000 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-9000-disk-0
qm set 9000 --ide2 local-lvm:cloudinit
qm set 9000 --boot c --bootdisk scsi0
qm set 9000 --serial0 socket --vga serial0
qm template 9000

**clusterctl.yaml**
providers:
  - name: in-cluster
    url: https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/v0.1.0/ipam-components.yaml
    type: IPAMProvider

PROXMOX_URL: "https://xxxx:8006"                       # The Proxmox VE host
PROXMOX_TOKEN: "capmox@pve!capi"                                # The Proxmox VE TokenID for authentication
PROXMOX_SECRET: "xxxxxx"                                    # The secret associated with the TokenID

PROXMOX_SOURCENODE: "hwj"                                     # The node that hosts the VM template to be used to provision VMs
TEMPLATE_VMID: "9000"                                          # The template VM ID used for cloning VMs
ALLOWED_NODES: "[hwj]"                        # The Proxmox VE nodes used for VM deployments
VM_SSH_KEYS: "ssh-ed25519 xxxxx"               # The ssh authorized keys used to ssh to the machines.

CONTROL_PLANE_ENDPOINT_IP: "192.168.3.210"                       # The IP that kube-vip is going to use as a control plane endpoint
NODE_IP_RANGES: "[192.168.3.211-192.168.3.220]"               # The IP ranges for Cluster nodes
GATEWAY: "192.168.3.1"                                         # The gateway for the machines network-config.
IP_PREFIX: "24"                                               # Subnet Mask in CIDR notation for your node IP ranges
DNS_SERVERS: "[192.168.3.1]"                              # The dns nameservers for the machines network-config.
BRIDGE: "vmbr0"                                               # The network bridge device for Proxmox VE VMs cat

BOOT_VOLUME_DEVICE: "scsi0"                                   # The device used for the boot disk.
BOOT_VOLUME_SIZE: "80"                                       # The size of the boot disk in GB.
NUM_SOCKETS: "1"                                              # The number of sockets for the VMs.
NUM_CORES: "4"                                                # The number of cores for the VMs.
MEMORY_MIB: "4096"                                            # The memory size for the VMs.

EXP_CLUSTER_RESOURCE_SET: "true"                              # This enables the ClusterResourceSet feature that we are using to deploy CNI
CLUSTER_TOPOLOGY: "true"                                      # This enables experimental ClusterClass templating

- Cluster-api-provider-proxmox version: 0.4.0
- Kubernetes version: (use `kubectl version`): 
Client Version: v1.29.5+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5+k3s1
- OS (e.g. from `/etc/os-release`): Centos 7.9

**Comment by mcbenjemaa** [comment] 2024-06-04 08:44
@abrahamhwj 
Please check the created machine cloud-init status

**Comment by abrahamhwj** [comment] 2024-06-05 01:13
> @abrahamhwj Please check the created machine cloud-init status
Thank you for your response. Initial inspection shows that cloud-init is working correctly:
In the Web interface, cloud-init works fine, and on the PVE host, inputting qm guest exec 102 -- /usr/bin/cloud-init status responds as follows:
`{
   "exitcode" : 0,
   "exited" : 1,
   "out-data" : "status: done\n"
}`
PS: The current integrated version introduces a crash in luthermonson/go-proxmox/virtual_machine.go/AgentExec when cloud-init is not ready. This issue is fixed in the main branch but has not been released yet.

**Comment by mcbenjemaa** [comment] 2024-06-11 09:35
We will try to get it fixed.

**Comment by mcbenjemaa** [comment] 2024-09-04 10:14
@abrahamhwj would you be able to help me reproduce this?

**Comment by wikkyk** [comment] 2024-11-05 11:19
I am closing this because we are on a go-proxmox release that is supposed to have a fix for this. Please feel free to reopen if the issue reappears.

**Closed by wikkyk** 2024-11-05 11:19 UTC
Labels: kind/bug
